export const GET_USER_COMMENTS_LIST = 'GET_USER_COMMENTS_LIST';
export const GET_USER_COMMENTS_LIST_SUCCESS = 'GET_USER_COMMENTS_LIST_SUCCESS';
export const GET_USER_COMMENTS_LIST_ERROR = 'GET_USER_COMMENTS_LIST_ERROR';
